---
title: "p8105_hw3_js5165"
author: "Jingqi Song"
date: "October 13, 2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Problem 1

```{r Problem1}
library(p8105.datasets)
p1_brfss=brfss_smart2010 %>% 
  janitor::clean_names() %>%
  separate(locationdesc, into = c("state", "county"), sep = " - ") %>%
  filter(topic=='Overall Health')%>%
  select(-class,-topic,-question,-sample_size,-locationabbr,-(confidence_limit_low:geo_location))%>%
  mutate(response = forcats::fct_relevel(response, c("Excellent", "Very good", "Good", "Fair", "Poor"))) %>% 
  spread(key = response, value = data_value)%>%
  janitor::clean_names()


#In 2002, which states were observed at 7 locations
p1_brfss%>%
  filter(year == 2002) %>% 
  group_by(state) %>% 
  summarize(count = n_distinct(county)) %>% 
  filter(count == 7)

#plot that shows the number of locations in each state from 2002 to 2010
p1_brfss%>%
  group_by(state, year) %>% 
  summarize(location_num = n_distinct(county)) %>% 
  ggplot(aes(x = year, y = location_num, color = state)) + 
  geom_smooth(se = FALSE) +
    labs(
    title = "Number of locations",
    x = "Year",
    y = "Number"
  )

#table for mean and standard deviation

#five-panel plot 
p1_average = p1_brfss %>%
  group_by(state, year) %>% 
  summarize(avg_excellent = mean(excellent), avg_very_good = mean(very_good), avg_good = mean(good), avg_fair = mean(fair), avg_poor = mean(poor)) 

p1_excellent = ggplot(p1_average, aes(x = year, y = avg_excellent, color = state)) +
  geom_smooth(se = FALSE) +
  theme(legend.position = "none") +
    labs(
    title = "Average Proportion of Excellent",
    x = "Year",
    y = "Average Proportion"
  )

p1_very_good = ggplot(p1_average, aes(x = year, y = avg_very_good, color = state)) +
  geom_smooth(se = FALSE) +
  theme(legend.position = "none") +
    labs(
      title = "Average Proportion of Very Good",
    x = "Year",
    y = "Average Proportion"
  )

p1_good = ggplot(p1_average, aes(x = year, y = avg_good, color = state)) +
  geom_smooth(se = FALSE) +
  theme(legend.position = "none") +
    labs(
      title = "Average Proportion of Good",
    x = "Year",
    y = "Average Proportion"
  )

p1_fair = ggplot(p1_average, aes(x = year, y = avg_fair, color = state)) +
  geom_smooth(se = FALSE) +
  theme(legend.position = "none") +
    labs(
      title = "Average Proportion of Fair",
    x = "Year",
    y = "Average Proportion"
  )

p1_poor = ggplot(p1_average, aes(x = year, y = avg_poor, color = state)) +
  geom_smooth(se = FALSE) +
  theme(legend.position = "none") +
    labs(
      title = "Average Proportion of Poor",
    x = "Year",
    y = "Average Proportion"
  )


```



In 2002, Connecticut, Florida and North Carolina were observed at 7 locations.
